version: '3'

services:
  qrcode-ascii-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qrcode-ascii-app
    ports:
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/__pycache__
    environment:
      - FLASK_ENV=production
